image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Haskell

    init: |
      mkdir -p /workspace/.ghcup/bin || true
      mkdir -p /workspace/.cabal || true
      export BOOTSTRAP_HASKELL_NONINTERACTIVE=1
      curl -sSL https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup -o /workspace/.ghcup/bin/ghcup
      chmod a+x /workspace/.ghcup/bin/ghcup
      # Install cabal
      ghcup install cabal 3.6.2.0
      ghcup set cabal 3.6.2.0
      # Install GHC
      ghcup install ghc 9.2.5
      ghcup set ghc 9.2.5

    command: |
      # Update cabal
      cabal update
      # Update ghcup
      ghcup upgrade
      # Show installed packages
      ghcup list

vscode:
  extensions:
    - haskell.haskell
